version: "3.7"
services:
  app:
    build:
      context: .
    container_name: fastapi_app
    ports:
      - '8000:8000'
    environment:
      - PYTHONPATH=/app
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:16.2-alpine3.19
    container_name: postgres_db
    ports:
      - 5433:${DB_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - PGPORT=${DB_PORT}
  redis:
    image: redis:7.0-alpine
    container_name: redis
    command:
      - --port ${REDIS_PORT}
    expose:
      - ${REDIS_PORT}
volumes:
  postgres_data:
