version: "3.7"
services:
  app:
    build:
      context: .
    container_name: fastapi_app
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - postgres
  postgres:
    image: postgres:16.2-alpine3.19
    container_name: postgres_db
    command: -p ${DB_PORT}
    expose:
      - ${DB_PORT}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
  redis:
    image: redis:7.0-alpine
    container_name: redis
    command:
      - --port ${REDIS_PORT}
    expose:
      - ${REDIS_PORT}
volumes:
  postgres_data:
