"""Database creation

Revision ID: 3dbfc45efd5f
Revises: 
Create Date: 2024-04-14 18:55:02.726091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import datetime


# revision identifiers, used by Alembic.
revision: str = '3dbfc45efd5f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    roles = op.create_table('roles',
    sa.Column('role_name', sa.String(), nullable=False, unique=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, primary_key=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    )
    op.bulk_insert(roles,
                   [{
                        'role_name': 'admin',
                        'id': 0,
                        'created_at': datetime.datetime.now(),
                        'updated_at': datetime.datetime.now()},
                    {
                        'role_name': 'owner',
                        'id': 1,
                        'created_at': datetime.datetime.now(),
                        'updated_at': datetime.datetime.now()
                        },
                       {'role_name': 'user',
                        'id': 2,
                        'created_at': datetime.datetime.now(),
                        'updated_at': datetime.datetime.now()}])
    op.create_table('users',
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )


    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
